services:
  api:
    environment:
      COHERE_API_KEY: ""
      COHERE_API_KEY_FILE: /run/secrets/cohere_api_key
    secrets:
      - cohere_api_key

secrets:
  cohere_api_key:
    file: ${COHERE_API_KEY_FILE:-./secrets/cohere_api_key}
